FROM nvidia/cuda:13.0.1-devel-ubuntu22.04

ENV DEBIAN_FRONTEND=noninteractive
ENV PYTHONUNBUFFERED=1

RUN apt-get update && apt-get install -y \
    python3 python3-venv python3-pip python3-dev \
    git ffmpeg libgl1 libglib2.0-0 libsm6 libxext6 libxrender-dev \
    build-essential wget curl \
    && rm -rf /var/lib/apt/lists/*

RUN python3 -m venv /venv
ENV PATH="/venv/bin:$PATH"

RUN pip install -U pip setuptools wheel

# PyTorch (совместим с CUDA 13 driver)
RUN pip install --no-cache-dir \
    torch torchvision torchaudio \
    --index-url https://download.pytorch.org/whl/cu121

# OpenMMLab installer
RUN pip install openmim

# mmcv wheel (без компиляции)
RUN mim install "mmcv>=2.0.0"

# mmaction
RUN pip install mmaction2

WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt

RUN pip install bitsandbytes>=0.48.0

COPY .. /app

ENV PYTHONPATH=/app
ENV CUDA_HOME=/usr/local/cuda
ENV LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH

RUN python -c "import torch;print(torch.__version__);print(torch.cuda.is_available())"

CMD ["tail","-f","/dev/null"]