services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: hakaton-ml
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - CUDA_VISIBLE_DEVICES=0
      - CUDA_HOME=/usr/local/cuda
    volumes:
      - ../src:/app/src
      - ../data:/app/data
      - ../models:/app/models
      - ../requirements.txt:/app/requirements.txt
    ports:
      - "8000:8000"
      - "7860:7860"
    command: tail -f /dev/null
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]