# Пути для данных
data_dir: "./data"
test_videos: "./data/test_videos"
results: "./data/results"
uploads: "./data/uploads"
logs: "./logs" 

pose_detector: "models/yolov8n-pose.pt"

glm4v_path: "models/glm-4v"

cache: "./cache"

# Пути для моделей
models: "./models"